vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        albums:
            uri_prefix: /images/albums
            upload_destination: '%kernel.project_dir%/public/images/albums'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        bands:
            uri_prefix: /images/bands
            upload_destination: '%kernel.project_dir%/public/images/bands'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
